name: autofix.ci

on:
  pull_request:
  push:
    branches:
      - master
      - v2

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Install Packages
        run: pnpm install

      - name: Eslint Check
        run: pnpm eslint

      - name: TypeScript Check
        run: pnpm typecheck

      - name: Run AutoFix
        uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c
